CREATE TABLE links (
    -- PG's auto incrementing IDs.
    id SERIAL PRIMARY KEY,

    -- Key generated by us.
    key VARCHAR (24) NOT NULL,

    -- The URL to link to.
    url VARCHAR NOT NULL,

    -- Domain, parsed out of the URL.
    domain VARCHAR (255) NOT NULL,

    -- Non-mandatory fields, editable by user.
    title VARCHAR (100) NOT NULL DEFAULT '',

    -- The key used is custom, and not generated by us.
    is_custom BOOLEAN NOT NULL DEFAULT false
);

-- Ensure `key` is unique.
CREATE UNIQUE INDEX links_key_unique_index on links(key);

-- Ensure `domain` is indexed. To rever lookup links for a domain.
CREATE INDEX links_domain_index on links(domain);
